language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7

before_script:
  - yes '' | pecl -q install -f mongo-stable
  - php --ri mongo
  - composer install --prefer-source --dev

script: ./vendor/bin/phpunit
