language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer install --prefer-source --dev

script: ./vendor/bin/phpunit
